server:
  servlet:
    context-path: /user
  port: 8080

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

blog.address: https://www.us.com
blog.author: Loren




